### ISSUE TITLE
session user id

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk_server#67]
Guardian.current_resource will return either `user.id` or `user_id`

**Comment by akinsey** [comment]
Upon login, current_resource will return a `timestamp` and `user_id` refer to the error below

```
[error] #PID<0.1327.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.1204.0>, stream id 13) terminated
Server: localhost:4000 (http)
Request: POST /api/login
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in EpochtalkServer.Models.UserIp.maybe_track/2
        (epochtalk_server 0.1.0) lib/epochtalk_server/models/user_ip.ex:36: EpochtalkServer.Models.UserIp.maybe_track(%{timestamp: ~N[2023-09-29 21:41:42.522929], user_id: 1}, "::1")
        (epochtalk_server 0.1.0) lib/epochtalk_server_web/plugs/track_ip.ex:30: anonymous fn/1 in EpochtalkServerWeb.Plugs.TrackIp.save_user_ip_to_database/1
        (elixir 1.14.4) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug 1.14.2) lib/plug/conn.ex:1836: Plug.Conn.run_before_send/2
        (plug 1.14.2) lib/plug/conn.ex:443: Plug.Conn.send_resp/1
        (epochtalk_server 0.1.0) lib/epochtalk_server_web/controllers/user.ex:1: EpochtalkServerWeb.Controllers.User.action/2
        (epochtalk_server 0.1.0) lib/epochtalk_server_web/controllers/user.ex:1: EpochtalkServerWeb.Controllers.User.phoenix_controller_pipeline/2
        (phoenix 1.7.2) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (epochtalk_server 0.1.0) lib/epochtalk_server_web/endpoint.ex:1: EpochtalkServerWeb.Endpoint.plug_builder_call/2
        (epochtalk_server 0.1.0) lib/epochtalk_server_web/endpoint.ex:1: EpochtalkServerWeb.Endpoint.call/2
        (phoenix 1.7.2) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /Users/kkid/Development/epochtalk_server/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/kkid/Development/epochtalk_server/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/kkid/Development/epochtalk_server/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
